// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopSphere.DatabaseModels;

#nullable disable

namespace ShopSphere.Migrations
{
    [DbContext(typeof(ShoppDbContext))]
    partial class ShoppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopSphere.DatabaseModels.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BrandId")
                        .HasName("PK__Brands__DAD4F05E3055B1B0");

                    b.HasIndex(new[] { "BrandName" }, "UQ__Brands__2206CE9BAC065FF8")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__51BCD7B7873298A3");

                    b.HasIndex(new[] { "UserId" }, "UQ__Cart__1788CC4DCD46C143")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B0A9F497D7D");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BBA104FB2");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E0CFCC62B5")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.CompareProduct", b =>
                {
                    b.Property<int>("CompareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompareId"));

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CompareId")
                        .HasName("PK__CompareP__1B61D63812A57A8B");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "ProductId" }, "UQ_Compare")
                        .IsUnique();

                    b.ToTable("CompareProducts");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCF07D61078");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D36C1AE98808");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Otp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OtpId")
                        .HasName("PK__OTPs__3143C4A3618B0195");

                    b.HasIndex("UserId");

                    b.ToTable("OTPs", (string)null);
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A380AC78842");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "TransactionId" }, "UQ__Payments__55433A6A8B87777A")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RetailerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6CD029A3E03");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RetailerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.ProductApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovalDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RetailerId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalId")
                        .HasName("PK__ProductA__328477F4B4A2A829");

                    b.HasIndex("AdminId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RetailerId");

                    b.ToTable("ProductApproval", (string)null);
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__ProductI__7516F70C56FD6FA7");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CE51D158A6");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "ProductId" }, "UQ_Review")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C1F2ED412");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105346BD0EF77")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNo" }, "UQ__Users__D6D73A86B73FD326")
                        .IsUnique()
                        .HasFilter("[MobileNo] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishlistId")
                        .HasName("PK__Wishlist__233189EB2D0D1DD5");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "ProductId" }, "UQ_Wishlist")
                        .IsUnique();

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Cart", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ShopSphere.DatabaseModels.Cart", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__UserId__04E4BC85");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.CartItem", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItems__CartI__08B54D69");

                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItems__Produ__09A971A2");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.CompareProduct", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("CompareProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ComparePr__Produ__00200768");

                    b.HasOne("ShopSphere.DatabaseModels.User", "User")
                        .WithMany("CompareProducts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ComparePr__UserI__7F2BE32F");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Order", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__UserId__0F624AF8");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.OrderDetail", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__1332DBDC");

                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Produ__14270015");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Otp", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.User", "User")
                        .WithMany("Otps")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__OTPs__UserId__17F790F9");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Payment", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__OrderI__2A164134");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Product", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__BrandI__6FE99F9F");

                    b.HasOne("ShopSphere.DatabaseModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__Catego__6EF57B66");

                    b.HasOne("ShopSphere.DatabaseModels.User", "Retailer")
                        .WithMany("Products")
                        .HasForeignKey("RetailerId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__Retail__70DDC3D8");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.ProductApproval", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.User", "Admin")
                        .WithMany("ProductApprovalAdmins")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductAp__Admin__1EA48E88");

                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("ProductApprovals")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductAp__Produ__1CBC4616");

                    b.HasOne("ShopSphere.DatabaseModels.User", "Retailer")
                        .WithMany("ProductApprovalRetailers")
                        .HasForeignKey("RetailerId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductAp__Retai__1DB06A4F");

                    b.Navigation("Admin");

                    b.Navigation("Product");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.ProductImage", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductIm__Produ__74AE54BC");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Review", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Product__25518C17");

                    b.HasOne("ShopSphere.DatabaseModels.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__245D67DE");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Wishlist", b =>
                {
                    b.HasOne("ShopSphere.DatabaseModels.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Wishlist__Produc__7A672E12");

                    b.HasOne("ShopSphere.DatabaseModels.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Wishlist__UserId__797309D9");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CompareProducts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductApprovals");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("ShopSphere.DatabaseModels.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CompareProducts");

                    b.Navigation("Orders");

                    b.Navigation("Otps");

                    b.Navigation("ProductApprovalAdmins");

                    b.Navigation("ProductApprovalRetailers");

                    b.Navigation("Products");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
